import { Button, VerticalBox } from "std-widgets.slint";

// import "@fonts/Readex Pro Variable.ttf"; // the language server has some issues with this line, the compiler has no problem with it
import "../assets/fonts/Readex Pro Variable.ttf";

export component AppWindow inherits Window {
    in property <image> logo: @image-url("@images/logo.png");

    preferred-height: 10cm;
    preferred-width: 10cm;
    title: "Acridotheres";

    in-out property <int> counter: 42;
    default-font-family: "Readex Pro";
    default-font-size: 4mm;
    default-font-weight: 400;

    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }

        Image {
            source: logo;
        }
    }

    background: #000;
    icon: logo;
}